### PR TITLE
[ID] Indonesian Translations

### PR DESCRIPTION
**Pull request by RoARene317**
This commit will add Indonesian Translations, to make user from Indonesia easier.

### CODE REVIEW

**Comment by RoARene317** [comment]
Closed because still missing most parts.

**Comment by SealsRock12** [comment]
Please use the [Weblate wesbite](https://librescore.ddns.net/) for translations.

**Comment by PeterNjeim** [comment]
It might be possible to merge this way actually, let me try

**Comment by PeterNjeim** [comment]
Your translations are now in the app

**Pull request merged**
